-- MySQL Script generated by MySQL Workbench
-- Fri May 23 14:47:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AppMusculacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AppMusculacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AppMusculacao` DEFAULT CHARACTER SET utf8 ;
USE `AppMusculacao` ;

-- -----------------------------------------------------
-- Table `AppMusculacao`.`gh_planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AppMusculacao`.`gh_planos` (
  `plano_ID` INT(10) NOT NULL,
  `plano_nome` VARCHAR(25) NOT NULL,
  `plano_precomes` DECIMAL(4) NOT NULL,
  `plano_descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`plano_ID`));


-- -----------------------------------------------------
-- Table `AppMusculacao`.`gh_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AppMusculacao`.`gh_usuarios` (
  `usuario_ID` INT(10) NOT NULL,
  `usuario_nome` VARCHAR(25) NOT NULL,
  `usuario_email` VARCHAR(120) NOT NULL,
  `usuario_password` VARCHAR(32) NOT NULL,
  `usuario_genero` VARCHAR(15) NOT NULL,
  `usuario_plano` INT(10) NOT NULL,
  `usuario_datacadastro` DATE NOT NULL,
  PRIMARY KEY (`usuario_ID`),
  INDEX `usuariosPlanos_idx` (`usuario_plano` ASC) VISIBLE,
  CONSTRAINT `usuariosPlanos`
    FOREIGN KEY (`usuario_plano`)
    REFERENCES `AppMusculacao`.`gh_planos` (`plano_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `AppMusculacao`.`gh_treinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AppMusculacao`.`gh_treinos` (
  `treino_ID` INT(10) NOT NULL,
  `treino_usuarioID` INT(10) NOT NULL,
  `treino_data` DATE NOT NULL,
  `treio_duracao` TIME NOT NULL,
  `treino_observacao` VARCHAR(150) NULL,
  PRIMARY KEY (`treino_ID`),
  INDEX `usuariosTreinos_idx` (`treino_usuarioID` ASC) VISIBLE,
  CONSTRAINT `usuariosTreinos`
    FOREIGN KEY (`treino_usuarioID`)
    REFERENCES `AppMusculacao`.`gh_usuarios` (`usuario_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `AppMusculacao`.`gh_mensagensContatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AppMusculacao`.`gh_mensagensContatos` (
  `mensagem_ID` INT(10) NOT NULL,
  `mensagem_usuarioID` INT(10) NOT NULL,
  `mensagem_remetenteNome` INT(45) NOT NULL,
  `mensagem_remetenteEmail` VARCHAR(120) NOT NULL,
  `mensagem_mensagem` VARCHAR(250) NOT NULL,
  `mensagem_dataEnvio` DATE NOT NULL,
  PRIMARY KEY (`mensagem_ID`),
  INDEX `usuariosMensagens_idx` (`mensagem_usuarioID` ASC) VISIBLE,
  CONSTRAINT `usuariosMensagens`
    FOREIGN KEY (`mensagem_usuarioID`)
    REFERENCES `AppMusculacao`.`gh_usuarios` (`usuario_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `AppMusculacao`.`gh_pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AppMusculacao`.`gh_pagamentos` (
  `pagamento_ID` INT(10) NOT NULL,
  `pagamento_usuarioID` INT(10) NOT NULL,
  `pagamento_numeroCartao` INT(16) NOT NULL,
  `pagamento_CVC` INT(3) NOT NULL,
  `pagamento_dataValidade` DATE NOT NULL,
  `pagamento_dataAssinatura` DATE NOT NULL,
  PRIMARY KEY (`pagamento_ID`),
  INDEX `usuariosMensagens_idx` (`pagamento_usuarioID` ASC) VISIBLE,
  CONSTRAINT `usuariosMensagens0`
    FOREIGN KEY (`pagamento_usuarioID`)
    REFERENCES `AppMusculacao`.`gh_usuarios` (`usuario_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `AppMusculacao`.`gh_musculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AppMusculacao`.`gh_musculos` (
  `musculos_ID` INT(10) NOT NULL,
  `musculo_nome` INT(45) NOT NULL,
  `musculo_generoAlvo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`musculos_ID`));


-- -----------------------------------------------------
-- Table `AppMusculacao`.`gh_exercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AppMusculacao`.`gh_exercicios` (
  `exercicio_ID` INT(10) NOT NULL,
  `exercicio_musculoID` INT(10) NOT NULL,
  `exercicio_nome` INT(45) NOT NULL,
  `exercicio_descricao` VARCHAR(150) NOT NULL,
  `exercicio_nivelDificuldade` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`exercicio_ID`),
  INDEX `exerciciosMusculos_idx` (`exercicio_musculoID` ASC) VISIBLE,
  CONSTRAINT `exerciciosMusculos`
    FOREIGN KEY (`exercicio_musculoID`)
    REFERENCES `AppMusculacao`.`gh_musculos` (`musculos_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `AppMusculacao`.`gh_itensTreinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AppMusculacao`.`gh_itensTreinos` (
  `item_ID` INT(10) NOT NULL,
  `item_treinoID` INT(10) NOT NULL,
  `item_exercicioID` INT(10) NOT NULL,
  `item_serie` INT(10) NOT NULL,
  `item_repeticao` INT(10) NULL,
  `item_carga` INT(10) NULL,
  PRIMARY KEY (`item_ID`),
  INDEX `treinosItens_idx` (`item_treinoID` ASC) VISIBLE,
  INDEX `itensTreinosExercicios_idx` (`item_exercicioID` ASC) VISIBLE,
  CONSTRAINT `treinosItens0`
    FOREIGN KEY (`item_treinoID`)
    REFERENCES `AppMusculacao`.`gh_treinos` (`treino_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `itensTreinosExercicios`
    FOREIGN KEY (`item_exercicioID`)
    REFERENCES `AppMusculacao`.`gh_exercicios` (`exercicio_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
